### ISSUE TITLE
Tiny Issue (decimal places)

### ISSUE THREAD

**Issue by bigstevehardy** [wubbl0rz/FiatChamp#12]
Is it possible to drop the amount of decimal places coming in ? 136.7014 is a little overkill :) perhaps just one would be sufficient ? 

And once again, thank you for such an awesome integration !!

**Comment by wubbl0rz** [comment]
yes i can round it to 1 or 2 digits. there is really no need to have it with this precision.  im currently working on reading system settings from home assistant. so km -> miles conversion can happen automagically if system is set to metric or imperial. with this update i can integrate rounded values too. 

btw you can do this already when using a lovelace card in the frontend that supports templating.

**Comment by wubbl0rz** [comment]
2.0.15 released. miles should be rounded to .2 digits now. 

location sensor now has home assistant zone (home,work, etc.) support. if the car is inside one of  this zones the location sensors now show the zone name. 

miles conversion should happen automatically if your home assistant uses imperial system.

# CHANGELOG

## 2.0.15 - 2022-10-19
- fix location sensor status.
- zone support. car location sensor now shows correct zone as defined in home assistant if car is in a 1000m radius of the zone. 
- autodetect from home assistant config if km -> miles conversion is needed. force conversion option still available.
- if using km -> miles conversion. rounded miles to .2 digits.
- 5sec delay between adding new sensors and pushing values to home assistant.
