### ISSUE TITLE
RAM Truck

### ISSUE THREAD

**Issue by mjalindahl** [wubbl0rz/FiatChamp#13]
I'm having an issue with this HA plugin.  I am not able to login - it says

`[13:11:28 INF] Mqtt connection successful
[13:11:30 ERR] System.Exception: Authentication failed. 403042 Forbidden Invalid LoginID`

I'm assuming this is because of the URLs/sites being different between Fiat/Jeep/RAM?  Do you happen to know what the RAM URL is, as I'm sure this is my mopar.com login.

Thanks!

**Comment by wubbl0rz** [comment]
yes i think they use different urls. last week someone reported that some jeeps work. but if RAM uses other urls it will not work. i think without changes thats not possible. 

if you have time and know how to use browser dev tools maybe we can make this work. you need to login to the RAM uconnect website (if RAM has a website) with dev tools open and check which urls they use. and then we just hope they use the same mechanism under the hood. 🙈 if that does not work maybe RAM has an android app and i could "extract" the urls from there.

**Comment by wubbl0rz** [comment]
this app looks nearly identical like the fiat app https://play.google.com/store/apps/details?id=com.fca.myconnect.ram.nafta&hl=en&gl=US ... possibly i could extract some information from the apk.

**Comment by wubbl0rz** [comment]
fyi i think it will work soon. maybe tomorrow if i got time to implement this.

**Comment by wubbl0rz** [comment]
@mjalindahl  are you interested in testing if it works with ram trucks now ? i can give you a link to a beta repository.

**Comment by mjalindahl** [comment]
Hi @wubbl0rz , yes I would love to test.  And I can test the browser stuff as well, if you haven't already gotten what you need.

**Comment by wubbl0rz** [comment]
@mjalindahl  try this repo https://github.com/wubbl0rz/FiatChampBeta its preview of version 3.0.0. no need to inspect website anymore i made a fake ram truck account and saved all urls and keys :grin:  login should work but i have no ram car so i could not check if sensors are correct etc. 

there will be more changes in this version besides ram support.

## 3.0.0 - 2022-10-20
- support for different brands. (fiat, jeep, ram, dodge)
  - fiat works
  - jeep should work out of the box
  - initial support for Ram Truck
  - dodge unknown
- instant state restore after home assistant reboot (retain mqtt state messages)
- battery charge now has % unit
- time to charge now has minutes unit
- added last update (time) sensor
- fixed many sensor icons and add device\_class
- added RefreshBatteryStatus button. its the same as DeepRefresh but with a better name.

**Comment by mjalindahl** [comment]
Hi @wubbl0rz.  Thanks for the quick turnaround on this.  It seems like the connection was successful, but I don't see any new entities.  I even restarted HA just in case.  Here's your addon log:

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[10:21:10 INF] Delay start for seconds: 1
[10:21:11 WRN] Ram support is experimental.
[10:21:12 INF] {
  "FiatUser": "",
  "FiatPw": "",
  "FiatPin": "",
  "MqttServer": "core-mosquitto",
  "MqttPort": 1883,
  "MqttUser": "addons",
  "MqttPw": "****************************************************************",
  "RefreshInterval": 15,
  "CarUnknownLocation": "away",
  "SupervisorToken": "****************************************************************************************************************",
  "Brand": 1,
  "HomeAssistantUrl": "http://supervisor/core",
  "StartDelaySeconds": 1,
  "AutoRefreshLocation": false,
  "AutoRefreshBattery": false,
  "EnableDangerousCommands": false,
  "ConvertKmToMiles": true,
  "DevMode": false,
  "UseFakeApi": false,
  "Debug": false
}
[10:21:12 INF] Now fetching new data...
[10:21:12 INF] Mqtt connection successful
[10:21:18 INF] Fetching COMPLETED. Next update in 15 minutes.
[10:23:17 INF] REFRESH SESSION`

**Comment by wubbl0rz** [comment]
"FiatUser": "", "FiatPw": "", "FiatPin": "" ... is this empty because you deleted it before posting or is it empty ? 

can you turn on debug and see if it gets any data from the Ram api ? there should be alot of output with data. pls be careful when posting debug logs here it may contain sensetive information like passwords etc.

**Comment by mjalindahl** [comment]
Yeah, I cleared those. The connection seems to be successful, but I’ll
check the debug log. I’ll post back in a bit.

**Comment by wubbl0rz** [comment]
@mjalindahl  any news :smile:  ? wanted to release 3.0.0 this weekend. but no hurry if Ram truck does not work at release we can fix it later.

**Comment by mjalindahl** [comment]
Hi @wubbl0rz 

Here's the debug log:

`s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[07:47:55 INF] Delay start for seconds: 1
[07:47:56 WRN] Ram support is experimental.
[07:47:57 INF] {
  "FiatUser": "",
  "FiatPw": "",
  "FiatPin": "",
  "MqttServer": "core-mosquitto",
  "MqttPort": 1883,
  "MqttUser": "addons",
  "MqttPw": "",
  "RefreshInterval": 15,
  "CarUnknownLocation": "away",
  "SupervisorToken": "",
  "Brand": 1,
  "HomeAssistantUrl": "http://supervisor/core",
  "StartDelaySeconds": 1,
  "AutoRefreshLocation": false,
  "AutoRefreshBattery": false,
  "EnableDangerousCommands": false,
  "ConvertKmToMiles": true,
  "DevMode": false,
  "UseFakeApi": false,
  "Debug": true
}
[07:47:57 DBG] {
  "FiatUser": "",
  "FiatPw": "",
  "FiatPin": "",
  "MqttServer": "core-mosquitto",
  "MqttPort": 1883,
  "MqttUser": "addons",
  "MqttPw": "",
  "RefreshInterval": 15,
  "CarUnknownLocation": "away",
  "SupervisorToken": "",
  "Brand": 1,
  "HomeAssistantUrl": "http://supervisor/core",
  "StartDelaySeconds": 1,
  "AutoRefreshLocation": false,
  "AutoRefreshBattery": false,
  "EnableDangerousCommands": false,
  "ConvertKmToMiles": true,
  "DevMode": false,
  "UseFakeApi": false,
  "Debug": true
}
[07:47:57 INF] Now fetching new data...
[07:47:57 INF] Mqtt connection successful
[07:47:58 DBG] {
  "CallId": "ff204e5a7db9487b945556dc50eabb59",
  "ErrorCode": 0,
  "ErrorDetails": null,
  "ErrorMessage": null,
  "ApiVersion": 2,
  "StatusCode": 200,
  "StatusReason": "OK",
  "Time": "2022-10-22T14:47:58.282+00:00"
}
[07:47:58 DBG] {
  "UID": "MOPUSEN_Mc220918012249316T",
  "SessionInfo": {
    "login_token": ""
  },
  "CallId": "2ded4ffe2fca4f70853044b51353e0e9",
  "ErrorCode": 0,
  "ErrorDetails": null,
  "ErrorMessage": null,
  "ApiVersion": 2,
  "StatusCode": 200,
  "StatusReason": "OK",
  "Time": "2022-10-22T14:47:58.839+00:00"
}
[07:47:59 DBG] {
  "id_token": "",
  "CallId": "4c1f1d9c7b5c4b9aa86ac63f53500d3c",
  "ErrorCode": 0,
  "ErrorDetails": null,
  "ErrorMessage": null,
  "ApiVersion": 2,
  "StatusCode": 200,
  "StatusReason": "OK",
  "Time": "2022-10-22T14:47:59.121+00:00"
}
[07:48:01 DBG] {
  "IdentityId": "us-east-1:7e74a5f7-934a-4afc-9ac7-a579143bddea",
  "Token": ""
}
[07:48:03 DBG] {
  "Userid": "MOPUSEN_Mc220918012249316T",
  "Version": 0,
  "Vehicles": []
}
[07:48:03 INF] Fetching COMPLETED. Next update in 15 minutes.`

And yes, any of the lines with "" I cleared manually.

**Comment by wubbl0rz** [comment]
thx 😄  but now i see why its not working. no vehicles are found and version is 0. 

```
"Version": 0, 
"Vehicles": []
```

so its not exactly the same as fiat. some calls must be different... this will be very hard for me to debug because i dont own a Ram car. would you be interested in helping with capturing some requests from the browser dev tools if i tell you what to capture 😄 ? 

PS: just to make sure. is the account verified and car works in the web interface ?

**Comment by mjalindahl** [comment]
Yes, I can use mopar.com to start my truck and get all the info. I also use
the uConnect app to start it, lock/unlock, etc.

Sure, I can help troubleshoot. I might not be available for the next few
hours, though.

**Comment by wubbl0rz** [comment]
yes don't hurry 😄 you are not using this website ? https://connect.ramtrucks.com/us/en/dashboard  

maybe i testet the wrong site. i thought this was the correct one.

**Comment by wubbl0rz** [comment]
i made a fake account on mopar.com ... this looks like a completely different service.  funny is i can login with the mopar.com credentials to https://connect.ramtrucks.com/us/en/dashboard ... so it uses some parts of the same service.

**Comment by wubbl0rz** [comment]
unfortunately its not possible. only the new uconnect sites api works with this addon. as far as i know its the only one hat has been "reverse engineered". for the other uconnect services only the manufacturer knows how they work.
