### ISSUE TITLE
Alfa Romeo Giulietta.

### ISSUE THREAD

**Issue by tomkolp** [wubbl0rz/FiatChamp#16]
Does not work for Alfa Romeo Giulietta.
![image](https://user-images.githubusercontent.com/39633242/198843976-4b42f8c7-589a-4150-9b9a-67dcf8a72cce.png)
`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[18:48:40 INF] {
  "FiatUser": "to***************",
  "FiatPw": "************",
  "FiatPin": "",
  "MqttServer": "core-mosquitto",
  "MqttPort": 1883,
  "MqttUser": "addons",
  "MqttPw": "****************************************************************",
  "RefreshInterval": 15,
  "CarUnknownLocation": "away",
  "SupervisorToken": "****************************************************************************************************************",
  "HomeAssistantUrl": "http://supervisor/core",
  "AutoRefreshLocation": false,
  "AutoRefreshBattery": false,
  "EnableDangerousCommands": false,
  "ConvertKmToMiles": false,
  "DevMode": false,
  "UseFakeApi": false,
  "Debug": false
}
[18:48:40 INF] Now fetching new data...
[18:48:41 INF] Mqtt connection successful
[18:48:45 INF] Fetching COMPLETED. Next update in 15 minutes.
[18:50:45 INF] REFRESH SESSION
[18:52:45 INF] REFRESH SESSION
[18:54:45 INF] REFRESH SESSION
[18:56:45 INF] REFRESH SESSION
[18:58:45 INF] REFRESH SESSION
[19:00:45 INF] REFRESH SESSION`

**Comment by wubbl0rz** [comment]
atleast it works without error but do not find any cars. so not all hope is lost to get it to work :grin:  which website you can use to control the car ? https://www.alfaromeoconnect.eu/ ?

**Comment by tomkolp** [comment]
> atleast it works without error but do not find any cars. so not all hope is lost to get it to work 😁 which website you can use to control the car ? https://www.alfaromeoconnect.eu/ ?

https://www.driveuconnect.eu/

**Comment by wubbl0rz** [comment]
this looks like a completely different service with completely different api. idk why there are so many of different "uconnect" things but it looks like an older/other version. under the hood they still using the same user database. does your car work with ? https://myalfaconnect.alfaromeo.com/ ?  this is the newest uconnect. if you can connect and use your car with this website then the addon should work and if not only minor tweaks should be necessary to make it work.

**Comment by tomkolp** [comment]
https://myalfaconnect.alfaromeo.com/ doesn't work for me because only new models are available.
The uconnect life android app works for me.

**Comment by wubbl0rz** [comment]
unfortunately then its not possible. only the new uconnect sites api works with this addon. as far as i know its the only one hat has been "reverse engineered" . the other uconnect services only the manufacturer knows how they work.
