### ISSUE TITLE
2020 Jeep Gladiator not authenticating

### ISSUE THREAD

**Issue by ItsRhen** [wubbl0rz/FiatChamp#17]
Just throwing this here as the integration says Jeeps should be supported.

I've verified my credentials, but still get:
System.Exception: Authentication failed. 403042 Forbidden Invalid LoginID

**Comment by wubbl0rz** [comment]
does it work with this site ? https://myuconnect.jeep.com/

**Comment by leosaker** [comment]
Great Addon!

In my case showed the following error:
"System.Exception: Authentication failed. 403120 Forbidden Account Temporarily Locked Out"

But works normally on the site: https://myuconnect.jeep.com/
Region: South America

**Comment by wubbl0rz** [comment]
ok maybe its the region.  he reported (https://github.com/wubbl0rz/FiatChamp/issues/11) that the addon is working but with an EU car. i will have a look if jeep use other urls and api keys for different regions.

**Comment by ItsRhen** [comment]
Apologies for the delay. I can log in successfully on that url. I don't see my vehicle under that account, but I'll look into it. I've also seen the same message @leosaker saw.

Happy to test or help further as I can, and appreciate the work!

**Comment by wubbl0rz** [comment]
i discovered they use different urls and different keys for EU or America ... so we need a region option in the addon config for each region.

**Comment by wubbl0rz** [comment]
pls update to 3.0.1 and try again :smile:  idk if everything works yet but login should work.

**Comment by ItsRhen** [comment]
Tried again this am. Same error. 🙃 I'm able to log in at the jeep url, but my vehicle app is pretty heavily "Mopar" branded. I wonder if they are segmented in a way, as I don't see my vehicle when I log in to the myuconnect url, just my account/profile.

Either way, I guess it still won't auth. Sort of at a loss.

**Comment by wubbl0rz** [comment]
if you cant control the car with https://myuconnect.jeep.com/ then the addon will not work even if the login is successful.  lets wait until leosaker has testet his login. i verified that i can login with a jeep fake account ... EU and NA account. i cant really test it because i dont have a jeep 😅

**Comment by leosaker** [comment]
Hi guys,
It was updated but still with this message: “[20:05:00 ERR] System.Exception: Authentication failed. 403120 Forbidden Account Temporarily Locked Out
   at FiatResponse.ThrowOnError(String message) in /home/runner/work/FiatChamp/FiatChamp/FiatChampAddon/FiatClient/FiatResponse.cs:line 31”

In myuconnect site there are north america and south america. I’m from Brazil.

**Comment by leosaker** [comment]
Full message: “[20:20:02 ERR] System.Exception: Authentication failed. 403120 Forbidden Account Temporarily Locked Out
   at FiatResponse.ThrowOnError(String message) in /home/runner/work/FiatChamp/FiatChamp/FiatChampAddon/FiatClient/FiatResponse.cs:line 31
   at FiatChamp.FiatClient.Login() in /home/runner/work/FiatChamp/FiatChamp/FiatChampAddon/FiatClient/FiatClient.cs:line 424
   at FiatChamp.FiatClient.LoginAndKeepSessionAlive() in /home/runner/work/FiatChamp/FiatChamp/FiatChampAddon/FiatClient/FiatClient.cs:line 372
   at Program.<>c__DisplayClass0_0.<<<Main>$>b__0>d.MoveNext() in /home/runner/work/FiatChamp/FiatChamp/FiatChampAddon/FiatClient/Program.cs:line 71
[20:20:02 INF] Fetching COMPLETED. Next update in 15 minutes.”

**Comment by wubbl0rz** [comment]
pls try 3.0.3 region settings didnt work correctly. 

settings are the same for NA or south america. i made a brazilian jeep account and login works.

if the problem is still there with 3.0.3 can look at the logs ? the long output with all the settings. does it say "Region": 0 or "Region": 1 ?

**Comment by leosaker** [comment]
PERFECT!!! It's works properly!! Congrats!!! Thanks a lot! 👍

**Comment by ItsRhen** [comment]
My account was able to auth as well! Now I'll just get Jeep to connect the vehicle there and hopefully will be in business.

Thanks a lot!
