### ISSUE TITLE
Willingness to Add Chrysler Vehicles

### ISSUE THREAD

**Issue by dblinick** [wubbl0rz/FiatChamp#21]
Hi,
Love this add-on - any openness to adding Chrysler vehicles to the mix - would love to be able to monitor my 22 Pacifica - but the core login is directly through MOPAR (https://www.mopar.com/en-us/sign-in.html) or via the uconnect app.  Not sure if this a deal breaker - but would be willing to act as a tester, just a little lost with the best way to explore and get access to the API.

**Comment by wubbl0rz** [comment]
i already tried (https://github.com/wubbl0rz/FiatChamp/issues/13)  but unfortunately its not working. mopar.com it a completely different older api. nobody expect the manufacturer knows how it work. only the newer uconnect api can work. 

- Fiat: https://myuconnect.fiat.com/
- Jeep: https://myuconnect.jeep.com/
- Ram: https://connect.ramtrucks.com/
- Dodge: https://connect.dodge.com/
- AlfaRomeo: https://myalfaconnect.alfaromeo.com/

has chrysler anything like this uconnect sites :thinking:  ?

**Comment by dblinick** [comment]
Unfortunately not... Thank you for the insight.  I will keep this pinned, and perhaps things will change in the future.
