### ISSUE TITLE
invalid loginID or password - :(

### ISSUE THREAD

**Issue by thimoura** [wubbl0rz/FiatChamp#33]
Hello friends)!

I would like to congratulate the team or the lone wolf responsible for the project! It will be amazing to be able to count on my Fiat information directly on my HA interface!

Unfortunately I haven't been able to take advantage of the project yet due to a silly authentication error.

I'm forwarding the log to possible support or even to report a possible bug.

______________________________________________________
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[20:50:48 INF] Delay start for seconds: 1
[20:50:49 INF] {
  "FiatUser": "mm******************",
  "FiatPw": "************",
  "FiatPin": "****",
  "MqttServer": "core-mosquitto",
  "MqttPort": 1883,
  "MqttUser": "addons",
  "MqttPw": "****************************************************************",
  "RefreshInterval": 15,
  "CarUnknownLocation": "away",
  "SupervisorToken": "****************************************************************************************************************",
  "Brand": "Fiat",
  "Region": "America",
  "HomeAssistantUrl": "http://supervisor/core",
  "StartDelaySeconds": 1,
  "AutoRefreshLocation": true,
  "AutoRefreshBattery": true,
  "EnableDangerousCommands": true,
  "ConvertKmToMiles": false,
  "DevMode": false,
  "UseFakeApi": false,
  "Debug": true
}
[20:50:49 DBG] {
  "FiatUser": "HIDE",
  "FiatPw": "HIDE",
  "FiatPin": "HIDE",
  "MqttServer": "core-mosquitto",
  "MqttPort": 1883,
  "MqttUser": "addons",
  "MqttPw": "HIDE",
  "RefreshInterval": 15,
  "CarUnknownLocation": "away",
  "SupervisorToken": "HIDE",
  "Brand": 0,
  "Region": 1,
  "HomeAssistantUrl": "http://supervisor/core",
  "StartDelaySeconds": 1,
  "AutoRefreshLocation": true,
  "AutoRefreshBattery": true,
  "EnableDangerousCommands": true,
  "ConvertKmToMiles": false,
  "DevMode": false,
  "UseFakeApi": false,
  "Debug": true
}
[20:50:49 INF] Now fetching new data...
[20:50:50 INF] Mqtt connection successful
[20:50:51 DBG] {
  "CallId": "HIDE",
  "ErrorCode": 0,
  "ErrorDetails": null,
  "ErrorMessage": null,
  "ApiVersion": 2,
  "StatusCode": 200,
  "StatusReason": "OK",
  "Time": "2022-12-09T23:50:50.954+00:00"
}
[20:50:51 DBG] {
  "UID": null,
  "SessionInfo": null,
  "CallId": "HIDE",
  "ErrorCode": 403042,
  "ErrorDetails": "invalid loginID or password",
  "ErrorMessage": "Invalid LoginID",
  "ApiVersion": 2,
  "StatusCode": 403,
  "StatusReason": "Forbidden",
  "Time": "2022-12-09T23:50:51.858+00:00"
}
[20:50:51 ERR] System.Exception: Authentication failed. 403042 Forbidden Invalid LoginID
   at FiatResponse.ThrowOnError(String message) in /home/runner/work/FiatChamp/FiatChamp/FiatChampAddon/FiatClient/FiatResponse.cs:line 31
   at FiatChamp.FiatClient.Login() in /home/runner/work/FiatChamp/FiatChamp/FiatChampAddon/FiatClient/FiatClient.cs:line 436
   at FiatChamp.FiatClient.LoginAndKeepSessionAlive() in /home/runner/work/FiatChamp/FiatChamp/FiatChampAddon/FiatClient/FiatClient.cs:line 384
   at Program.<>c__DisplayClass0_0.<<<Main>$>b__0>d.MoveNext() in /home/runner/work/FiatChamp/FiatChamp/FiatChampAddon/FiatClient/Program.cs:line 72
[20:50:52 INF] Fetching COMPLETED. Next update in 15 minutes.
______________________________________________________

It may have to do with my authentication that used to be a social login through Gmail and I simply reset the password and registered a new one via email.

Authentication via myuconnect.fiat.com works perfectly!

Thanks for your help and congratulations again on the amazing project!

**Comment by wubbl0rz** [comment]
ah i see 😐 ... my fiat is EU. i need to replace some urls that it works for NA. will fix it in the next few days.

**Comment by thimoura** [comment]
Perfect!  If I can help with anything, even providing authentication credentials, I'll be happy to help!

**Comment by wubbl0rz** [comment]
can you try again with 3.0.8 ?

**Comment by wubbl0rz** [comment]
can you try again with 3.0.8 ?

**Comment by thimoura** [comment]
Hi there! You are amazing! Every sensor and states is a fully function! 
Thank so much about the resolution!

I here if you need some tests!
