### ISSUE TITLE
Not finding vehicle (Jeep)

### ISSUE THREAD

**Issue by wtown42** [wubbl0rz/FiatChamp#34]
I have a Jeep Grand Cherokee which is controllable through the https://www.mopar.com/jeep/en-us/my-vehicle/dashboard.html (Americas) website, but does not show up in FiatChamp. In the addon debug logs, all the authentication seems to work, but at the end it shows vehicles [ ]. Any idea why it would not be showing up?

**Comment by wubbl0rz** [comment]
yes mopar.com will not work. its a completely different api and older uconnect version. 

check if your car works here:
Jeep: https://myuconnect.jeep.com/

**Comment by wtown42** [comment]
When I sign in at myuconnect.jeep.com, it brings up a link that redirects me to www.mopar.com, where I have to sign in again. Maybe the car is too old (2018) for the new portal?

**Comment by wubbl0rz** [comment]
look like it 😐 unfortunately it will not work
