### ISSUE TITLE
Mqtt only

### ISSUE THREAD

**Issue by neutrino85** [wubbl0rz/FiatChamp#35]
Hello,
Thank you for your brilliant work.
Is there a way to use it only with MQTT in standalone mode ?
I'm not using HA and i don't want to run it just for your addon.
Thanks for all.

**Comment by AirBeeSee** [comment]
u could try using iobroker and this adapter for fiat. 
https://github.com/TA2k/ioBroker.fiat
using mqtt and has all the same remote / sensor like this add-on

**Comment by neutrino85** [comment]
Sounds good but doesn't work.
Seems i'm going to learn c#.

**Comment by AirBeeSee** [comment]
This iobroker adapter run on my system since 09/2021 without any problem.
