### ISSUE TITLE
Kw used

### ISSUE THREAD

**Issue by pierpaolo1972** [wubbl0rz/FiatChamp#36]
Hi, thanks for the work you've done. Really great. I wanted to know if there is any value related to the power used or total power loaded. Thank you

**Comment by wubbl0rz** [comment]
no there is nothing like this in the official api. in the app they have eco reports (which is a different thing and not yet supported)  where you can see average kwh/100km and distance of the last trip. so maybe its possible to calculate power used. but not yet possible in home assistant 😀

**Comment by pierpaolo1972** [comment]
Thanks so much.
