### ISSUE TITLE
Stop charging

### ISSUE THREAD

**Issue by dibi73** [wubbl0rz/FiatChamp#6]
Thank you so much for writing this addin.
Is there an option to stop charging (eg when the charging level has reached 80%)
And perhaps you xould post the automation you mentioned after the charging has started?

**Comment by wubbl0rz** [comment]
hi :smile:  

i would love to offer this option. unfortunately its not possible over the fiat api. the official app lacks this option too. they only have a command to start charging ... and no command to stop it. i do not know why they think thats a good design. :woozy_face: 

you can see my 2 automations here. its not possible with the addon alone i have a charger that has an api and can be controller over wifi:

![image](https://user-images.githubusercontent.com/30373916/194615315-6a2cc793-bf10-4a0c-8a44-dba199d808f0.png)
![image](https://user-images.githubusercontent.com/30373916/194616421-e0ea0dc3-1946-4d42-bf55-e0ad4fc43ed4.png)

**Comment by wubbl0rz** [comment]
@dibi73  i have an idea. are you using the "scheduled charging" feature from uconnect ? i dont know how its called. the one where you have some sort of calendar and can insert starting times. if not ... maybe we can "hijack" this feature to stop charging :exploding_head:  i could create a temporary charging schedule of 1 minute (when battery level is >=80%) and then it should turn off.

**Comment by dibi73** [comment]
Thank you very much. I get my wallbox (Wattpilot) next week and i think i can bring it into home assistant. Then i can do the charging more easily.
  

  

  

  

  
  
  
  
>

**Comment by wubbl0rz** [comment]
yes i think thats the better way of doing this. monitoring battery status from the car and remote turning the wallbox on/off. better as hijacking the scheduling feature 😁 remember "deeprefresh" is the fiat language for battery status update. so call the "deeprefresh" function every ~15min and the car should sent its current battery level.
